# Generated by Django 3.2.4 on 2021-06-11 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpages', '0005_auto_20210611_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, null=True)),
                ('project_name', models.CharField(max_length=255, null=True)),
                ('rating', models.CharField(max_length=255, null=True)),
                ('sensei_name', models.CharField(max_length=255, null=True)),
                ('completion_percentage', models.IntegerField()),
                ('comment', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webpages.project')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
