# Generated by Django 3.2.4 on 2021-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityform',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
