# Generated by Django 3.2.4 on 2021-06-11 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpages', '0005_auto_20210611_1755'),
        ('activityform', '0002_activityform_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityform',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webpages.project'),
        ),
        migrations.AlterField(
            model_name='activityform',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
