# Generated by Django 3.2.4 on 2021-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0003_auto_20210611_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityform',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='activityform',
            name='student_name',
        ),
        migrations.AlterField(
            model_name='activityform',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activityform',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
