# Generated by Django 3.2.4 on 2021-06-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20210611_1755'),
        ('activityform', '0004_auto_20210611_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('sensei_name', models.CharField(max_length=255, null=True)),
                ('completion_percentage', models.IntegerField()),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.project')),
                ('topic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityForm',
        ),
    ]
