# Generated by Django 3.2.4 on 2021-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0006_alter_activity_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='topic_id',
            field=models.IntegerField(null=True),
        ),
    ]
