# Generated by Django 3.2.4 on 2021-06-12 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpages', '0005_auto_20210611_1755'),
        ('activityform', '0007_auto_20210612_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.project'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='topic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.topic'),
        ),
    ]
