# Generated by Django 3.2.4 on 2021-06-13 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activityform', '0008_auto_20210612_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='student_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
