# Generated by Django 3.2.4 on 2021-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0011_alter_activity_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
