# Generated by Django 3.2.4 on 2021-06-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20210611_1755'),
        ('activityform', '0012_alter_activity_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webpages.project'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='topic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webpages.topic'),
        ),
    ]
