# Generated by Django 3.2.4 on 2021-06-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0014_auto_20210613_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user_id',
            new_name='user',
        ),
    ]
