# Generated by Django 3.2.4 on 2021-06-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20210611_1755'),
        ('activityform', '0016_rename_user_activity_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.project'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sensei_name',
            field=models.CharField(choices=[('Anurag Rawat', 'Anurag Rawat'), ('Leonie Dennett', 'Leonie Dennett'), ('Elena Bardho', 'Elena Bardho'), ('Goundo Sidibe', 'Goundo Sidibe'), ('Siddhant Dalal', 'Siddhant Dalal'), ('Manan Adhvaryu', 'Manan Adharvyu')], max_length=255, null=True),
        ),
    ]
