# Generated by Django 3.2.4 on 2021-06-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_alter_project_topic_id'),
        ('activityform', '0017_auto_20210615_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='topic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.topic'),
        ),
    ]
