# Generated by Django 3.2.4 on 2021-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0019_auto_20210619_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='completion_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
