# Generated by Django 3.2.4 on 2021-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0020_auto_20210704_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sensei_name',
            field=models.CharField(choices=[('Anurag Rawat', 'Anurag Rawat'), ('Leonie Dennett', 'Leonie Dennett'), ('Elena Bardho', 'Elena Bardho'), ('Goundo Sidibe', 'Goundo Sidibe'), ('Siddhant Dalal', 'Siddhant Dalal'), ('Manan Adhvaryu', 'Manan Adharvyu'), ('Marta Garcia', 'Marta Garcia'), ('Omar Veiga', 'Omar Veiga'), ('Simran Tulsiani', 'Simran Tulsiani'), ('Ilham Esse', 'Ilham Esse'), ('Istabraq Ahmed', 'Istrabraq Ahmed'), ('Manali Ballewar', 'Manali Ballewar'), ('Polly Thomas', 'Polly Thomas')], max_length=255, null=True),
        ),
    ]
