# Generated by Django 3.2.9 on 2021-11-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0022_alter_activity_sensei_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sensei_name',
            field=models.CharField(choices=[('Anurag Rawat', 'Anurag Rawat'), ('Siddhant Dalal', 'Siddhant Dalal'), ('Manan Adhvaryu', 'Manan Adharvyu'), ('Marta Garcia', 'Marta Garcia'), ('Omar Veiga', 'Omar Veiga'), ('Simran Tulsiani', 'Simran Tulsiani'), ('Ilham Esse', 'Ilham Esse'), ('Istabraq Ahmed', 'Istrabraq Ahmed'), ('Kyan ', 'Kyan '), ('Ayman ', 'Ayman ')], max_length=255, null=True),
        ),
    ]
