# Generated by Django 3.2.9 on 2021-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0024_auto_20211127_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sensei_name',
            field=models.CharField(choices=[('Anurag Rawat', 'Anurag Rawat'), ('Siddhant Dalal', 'Siddhant Dalal'), ('Marta Garcia', 'Marta Garcia'), ('Omar Veiga', 'Omar Veiga'), ('Simran Tulsiani', 'Simran Tulsiani'), ('Ilham Esse', 'Ilham Esse'), ('Istabraq Ahmed', 'Istrabraq Ahmed'), ('Kyan Ung', 'Kyan Ung'), ('Ayman El Behri', 'Ayman El Behri'), ('Amber Barakat', 'Amber Barakat')], max_length=255, null=True),
        ),
    ]
