# Generated by Django 4.0.1 on 2022-01-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0025_alter_activity_sensei_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='comment',
            new_name='ninja_comment',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='completion_percentage',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sensei_comment',
            field=models.TextField(blank=True),
        ),
    ]
