# Generated by Django 4.0.1 on 2022-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0026_rename_comment_activity_ninja_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_completed',
            field=models.BooleanField(),
        ),
    ]
