# Generated by Django 4.0.1 on 2022-02-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0028_alter_activity_sensei_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='rating',
        ),
        migrations.AlterField(
            model_name='activity',
            name='sensei_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
