# Generated by Django 4.0.1 on 2022-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0030_activity_laptop_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='laptop_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
