# Generated by Django 4.0.1 on 2022-05-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0031_alter_activity_laptop_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='sensei_comment',
        ),
    ]
