# Generated by Django 4.0.1 on 2022-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityform', '0032_remove_activity_sensei_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='laptop_num',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
