# Generated by Django 3.2.4 on 2021-06-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artek',
        ),
        migrations.DeleteModel(
            name='Circuits',
        ),
        migrations.DeleteModel(
            name='Lego',
        ),
        migrations.DeleteModel(
            name='Scratch',
        ),
        migrations.DeleteModel(
            name='Typing',
        ),
    ]
