# Generated by Django 3.2.4 on 2021-06-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_accounts_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
