# Generated by Django 4.0.1 on 2022-04-04 22:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solution_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
